name: monitoring

services:
  beszel:
    image: henrygd/beszel:${BESZEL_TAG:-latest}
    container_name: beszel
    restart: unless-stopped
    logging:
      driver: ${LOGGING_DRIVER:-local}
    environment:
      APP_URL: ${BESZEL_APP_URL:-http://localhost:8090}
    ports:
      - ${PORT_BESZEL_HTTP:-8090}:8090
    volumes:
      - ${CONFIG_DIR:?CONFIG_DIR is required}/beszel/hub:/beszel_data
      - ${CONFIG_DIR:?CONFIG_DIR is required}/beszel/socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:${BESZEL_AGENT_TAG:-latest}
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    logging:
      driver: ${LOGGING_DRIVER:-local}
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: ${BESZEL_HUB_URL:-http://localhost:8090}
      TOKEN: ${BESZEL_AGENT_TOKEN:-}
      KEY: ${BESZEL_AGENT_KEY:-}
    volumes:
      - ${CONFIG_DIR:?CONFIG_DIR is required}/beszel/agent:/var/lib/beszel-agent
      - ${CONFIG_DIR:?CONFIG_DIR is required}/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
